### ISSUE TITLE
Guide how to actually get started developing in the different supported browsers

### ISSUE THREAD

**Issue by BjoernRave** [nyaggah/bedframe#334]
I just used the `bedframe make` command to gernerate a new project and was amazed by the setup, very nice job on that.

Now I have this project and when I run `pnpm dev` i only see this url: `http://localhost:5173/`, but when entering the page i see nothing.

Now I am not sure how to get started developing my extension in firefox, because usually you need to load some files

**Comment by JoeyDoey** [comment]
Hey @BjoernRave ! Thank you! Glad you liked it so far :) 
I need to put together a quickstart guide. I'll get that up for you soon. 
in the meantime, e.g. to test an extension for Chrome:

- run `pnpm build chrome`
<img width="1920" alt="pnpm-build-chrome" src="https://github.com/nyaggah/bedframe/assets/284415/7b34b83f-2930-4e7a-9d45-b75e341c10e7">

- open Chrome browser and go to [chrome://extensions/](chrome://extensions/)
- toggle the "Developer mode" switch to on (this reveals additional dev actions)
![turn-on-developer-mode-in-extensions](https://github.com/nyaggah/bedframe/assets/284415/b7eb4ab2-8332-451a-a612-ac71ffdd3ed2)
- select "Load unpacked" and find your extension dist directory. by default the dist for the specific browser will be at `project-name/dist/<browser>` so for Chrome, select the `project-name/dist/chrome` directory
![load-unpacked](https://github.com/nyaggah/bedframe/assets/284415/64e06071-433e-4850-9f86-61054519ccec)
- pin the extension (for easier access when dev-ing)
![pin-extension-for-easier-access](https://github.com/nyaggah/bedframe/assets/284415/f12cfaa8-efe4-4183-bded-27a5d2c8774f)
...
- you can navigate to the options page by right-clicking the extension icon and selecting "options"
![right-click-extension-icon-to-view-options](https://github.com/nyaggah/bedframe/assets/284415/6403d773-47dc-44c6-be25-9c8d8452287a)


nb:
- you can't really go directly to that localhost URL to load up the extension.
- one of the main goals of Bedframe is to make it easy to have HMR when developing for all the browsers you're targetting. If you already ran `pnpm dev` you likely saw this notice

[<img width="761" alt="image" src="https://github.com/nyaggah/bedframe/assets/284415/7d914a6b-31a6-4cbb-a73e-0ae2654b45c7">](https://www.youtube.com/watch?v=kSLbb1WxcOQ)

I'm looking into a fix for that so in the meantime just the `pnpm build` commands are working. 
specifically I need to update the [`getManifest` function](https://github.com/nyaggah/bedframe/blob/main/packages/core/src/lib/get-manifest.ts#L24)
