### ISSUE TITLE
Vue support?

### ISSUE THREAD

**Issue by AcidRaZor** [nyaggah/bedframe#466]
Hey, really like where this is going, however I would love to get Vue support in this. 

Had trouble getting React going, I have Vite 5.3.1 but this depends on 5.2.6?

Currently doing my extension with CXR, but would love to be able to support all browsers and utilize the versioning/publish aspect as well.

Can't wait for more progress on this!

**Comment by JoeyDoey** [comment]
Hey @AcidRaZor ! glad you're digging it so far!

> Had trouble getting React going, I have Vite 5.3.1 but this depends on 5.2.6?

Maybe when you first create the project, you could try update the dependencies.

You could also just start from a fresh vite with react (or vue, etc) install (`npm create vite`) and add `@bedframe/cli` and `@bedframe/core`. then create the manifests and the bedframe config (similar to what's generated by the cli.

> would love to get Vue support in this.

Bedframe uses Vite and CRX under the hood which both support Vue. Here's a quick example repo with `Vite` + `Vue` + `TS`: https://github.com/nyaggah/bedframe/tree/main/examples/popup-vue-ts

This is the default [create-vite/template-vue-ts](https://github.com/vitejs/vite/tree/main/packages/create-vite/template-vue-ts) template with bedframe deps + files included. 

You can start from this and add the dependencies and organize the folder structure.

I think the main things are:
- move the root to `src`
- move the index.html the root to `src/pages/`
- create a `src/manifests/` dir and have you manifests there
- reference the example repo.

hopefully that's helpful. #docsComingSoon 🙃
