### ISSUE TITLE
ETA Svelte?

### ISSUE THREAD

**Issue by Rubyer77** [nyaggah/bedframe#512]
I need to start an extension in a few days. Do you have an ETA for Svelte?

It's 72.8% desired and admired so it will grow: 

https://survey.stackoverflow.co/2024/technology/#most-popular-technologies-webframe-prof

**Comment by JoeyDoey** [comment]
Hey @Rubyer77 Thanks for checking out Bedframe! 

You should be able to build with all meta-frameworks right now. 

The Bedframe CLI project generator happy path right now is just React w/ TS but if you start a new Vite project (with any of the supported frameworks) you can add the Bedframe deps and be good to go. Take a look at the examples.

I've thrown up a **Svelte popup extension with TypeScript** base starter in the examples here as well: https://github.com/nyaggah/bedframe/tree/main/examples/popup-svelte-ts

Hope that helps!
